#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

# Fix 11 — only compile dock sources in editor builds
if env.editor_build:
    env.add_source_files(env.editor_sources, "*.cpp")
    env.add_source_files(env.editor_sources, "ai/*.cpp")
